---
orgs:
  - name: <github_organization_name>
    pem:  <path_to_pem>
    app_id:
    installation_id:
    # If using GitHub Enterprise, set base_url.
    # GitHub Enterprise is supported by these examples: python-pygithub
    # base_url: https://ghe.example.com/api/v3
